# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "spud_photos"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Greg Woods"]
  s.date = "2012-02-18"
  s.email = "greg@westlakedesign.com"
  s.files = [
    "config/application.rb",
    "config/boot.rb",
    "config/routes.rb",
    "lib/spud_photos.rb",
    "lib/spud_photos/configuration.rb",
    "lib/spud_photos/engine.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Spud Photo Album Engine"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<spud_core>, [">= 0.5.2"])
    else
      s.add_dependency(%q<spud_core>, [">= 0.5.2"])
    end
  else
    s.add_dependency(%q<spud_core>, [">= 0.5.2"])
  end
end

