# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "spud_photos"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Greg Woods"]
  s.date = "2012-03-30"
  s.email = "greg@westlakedesign.com"
  s.files = [
    "app/assets/images/spud/photos/buttons/cog_16x16.png",
    "app/assets/images/spud/photos/buttons/x_16x16.png",
    "app/assets/images/spud/photos/photo_albums_thumb.png",
    "app/assets/images/spud/photos/photo_albums_thumb@2x.png",
    "app/assets/javascripts/photo_albums.js",
    "app/assets/javascripts/photo_galleries.js",
    "app/assets/javascripts/spud/admin/photo_albums.js",
    "app/assets/javascripts/spud/admin/photo_galleries.js",
    "app/assets/javascripts/spud/admin/photos.js",
    "app/assets/stylesheets/photo_albums.css",
    "app/assets/stylesheets/photo_galleries.css",
    "app/assets/stylesheets/spud/admin/photo_albums.css",
    "app/assets/stylesheets/spud/admin/photo_galleries.css",
    "app/assets/stylesheets/spud/admin/photos.css",
    "app/controllers/photo_albums_controller.rb",
    "app/controllers/photo_galleries_controller.rb",
    "app/controllers/spud/admin/photo_albums_controller.rb",
    "app/controllers/spud/admin/photo_galleries_controller.rb",
    "app/controllers/spud/admin/photos_controller.rb",
    "app/helpers/photo_albums_helper.rb",
    "app/helpers/photo_galleries_helper.rb",
    "app/helpers/spud/admin/photo_albums_helper.rb",
    "app/helpers/spud/admin/photo_galleries_helper.rb",
    "app/helpers/spud/admin/photos_helper.rb",
    "app/models/spud_photo.rb",
    "app/models/spud_photo_album.rb",
    "app/models/spud_photo_gallery.rb",
    "app/views/layouts/spud/admin/spud_photos.html.erb",
    "app/views/photo_albums/index.html.erb",
    "app/views/photo_albums/show.html.erb",
    "app/views/photo_galleries/index.html.erb",
    "app/views/photo_galleries/show.html.erb",
    "app/views/spud/admin/photo_albums/_album.html.erb",
    "app/views/spud/admin/photo_albums/_form.html.erb",
    "app/views/spud/admin/photo_albums/destroy.js.erb",
    "app/views/spud/admin/photo_albums/edit.html.erb",
    "app/views/spud/admin/photo_albums/index.html.erb",
    "app/views/spud/admin/photo_albums/new.html.erb",
    "app/views/spud/admin/photo_galleries/_form.html.erb",
    "app/views/spud/admin/photo_galleries/destroy.js.erb",
    "app/views/spud/admin/photo_galleries/edit.html.erb",
    "app/views/spud/admin/photo_galleries/index.html.erb",
    "app/views/spud/admin/photo_galleries/new.html.erb",
    "app/views/spud/admin/photos/_form.html.erb",
    "app/views/spud/admin/photos/_photo.html.erb",
    "app/views/spud/admin/photos/destroy.js.erb",
    "app/views/spud/admin/photos/edit.html.erb",
    "app/views/spud/admin/photos/index.html.erb",
    "app/views/spud/admin/photos/new.html.erb",
    "config/application.rb",
    "config/boot.rb",
    "config/routes.rb",
    "lib/spud_photos.rb",
    "lib/spud_photos/configuration.rb",
    "lib/spud_photos/engine.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Spud Photos Engine"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<spud_core>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
    else
      s.add_dependency(%q<spud_core>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
    end
  else
    s.add_dependency(%q<spud_core>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
  end
end

